首先进入M3.1/xuan81400 
***python manage.py runserver 127.0.0.1:2333*** 这样服务就可以被启动了

略微逆天的一次经历重写之后发现了之前好多忽视的东西最逆天的就是之前没注意还能跑
更逆天的是我回退了版本之后 原来的也跑不出来了 请务必告诉学弟难道真的有程序能依靠bug运行吗？
